source 'https://rubygems.org'

gem 'rails', '3.2.6'
gem 'pg'
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end
group :development do
  gem 'rails-erd'
  gem 'mailcatcher'
  gem 'faker'
end
gem 'jquery-rails'
gem 'rails_admin'
gem 'devise'
gem 'thin'
gem 'execjs'
gem 'therubyracer'
gem 'twitter-bootstrap-rails'
gem 'foreigner'
gem 'cancan'
gem 'icalendar'
gem 'uuidtools'
gem 'eco'
gem 'fullcalendar-rails'
gem 'gon'
gem 'carrierwave'
gem 'simple_form'
gem 'client_side_validations'
gem 'coffeebeans'
gem 'validates_timeliness', '~> 3.0'