development:
  host: /tmp
  adapter: postgresql
  template: template0
  encoding: utf-8
  database: shm
  username: shm
  password: shm
  port: 5432
  pool: 5

test:
  host: /tmp
  adapter: postgresql
  template: template0
  encoding: utf-8
  database: shm_test
  username: shm
  password: shm
  port: 5432
  pool: 5

production:
  adapter: postgresql
  template: template0
  encoding: utf-8
  database: shm
  username: shm
  password: shm
  pool: 5